### ISSUE TITLE
Align operations examples in site to new structure

### ISSUE THREAD

**Issue by oritstone** [openscore/openscore.github.io#40]
Need to align all our operations slang examples to the new syntax of operation.
- Each operation file should have the same name as the name of the operation
- The operation structure should start with the attribute *operation:*
- Below there should be a *name* attribute with the name of the operation.

Example:
```
namespace: user.ops

operation:
  name: operation_with_data
  inputs:
    - input1
  action:
    python_script: |
            # this is python amigos!!
            print input1
            print input2
  outputs:
    - output1: input1
  results:
    - SUCCESS: 1 != 123456
    - FAILURE
```
