### ISSUE TITLE
Need to fix site examples to use lists instead of maps for tasks

### ISSUE THREAD

**Issue by orius123** [openscore/openscore.github.io#46]
**i.e**
```yaml
workflow:
  - task_1:
      ...
  - task_2:
      ...
```

**instead of:**
```yaml
workflow:
  task_1:
    ...
  task_2:
    ...
```
